### ISSUE TITLE
Break time

### ISSUE THREAD

**Issue by alexregier** [Sese-Schneider/ha-personio#2]
It would be cool to have breaks supported.

Ending an attendance block and creating a new one it not really sufficient if you only want to track a break, e.g. for lunch.
Maybe as a switch itself. But those switches would need to be synced somehow, e.g. that turning the "main attendance" switch off also deactivates the break automatically in case it's still turned on.

**Comment by Sese-Schneider** [comment]
@alexregier can you elaborate further why just ending an attendance block is not sufficient?

**Comment by Sese-Schneider** [comment]
@alexregier can you elaborate further why just ending an attendance block is not sufficient?

**Comment by Sese-Schneider** [comment]
Turning it on and off will provide a correct entry.

![image](https://user-images.githubusercontent.com/14337484/217596706-426238b9-6852-4635-bc3e-c8580b675f4e.png)

**Comment by alexregier** [comment]
Oh great!
I thought one would need to explicitly add a break when using the API.
Good to know that this also works :)
Thank you!
